T: 30
alpha: 0.003
batch_size: 128
beta: 1.28
data_folder: ~/SpiNNCloud/Code/data/
dataset: mnist
deterministic: false
device: cpu
dt: 1
encoding: latency_snntorch
epochs: 2
loss_type: ce_temporal
lr: 0.01
model: eventprop
mu:
  - 1
  - 1.0
n_hid: 100
optimizer: adam
print_freq: 100
resolve_silent: true
seed: 0
simple_lif: false
t_max:
t_min: 2.0
tau_m: 20.0
tau_s: 5.0
use_fluct_init: false
xi: 0.1
